services:
  api:
    build:
      context: ./app
    ports:
      - 5000:8000
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MISTRAL_OCR_KEY=${MISTRAL_OCR_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URL=mongodb+srv://admin:I8INtdhMBRIfYpo7@cluster0.rfbjo.mongodb.net/financial_ocr_db?retryWrites=true&w=majority
      - DB_NAME=financial_ocr_db
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - type: bind
        source: ./uploads
        target: /app/uploads
      - type: bind
        source: ./app
        target: /app
